apiVersion: v1
kind: Service
metadata:
 name: test-product
spec:
 type: NodePort
 selector:
   app: tester
   env: production
 ports:
 - nodePort: 32222
   protocol: TCP
   port: 80
   targetPort: 80

