apiVersion: v1
kind: Service
metadata:
 name: test-product
spec:
 type: NodePort
 selector:
   app: test-app
   env: prod
 ports:
 - name: http
   protocol: TCP
   port: 3000
   targetPort: 3000
   nodeport:32222
